repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.411
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.16
    hooks:
      # Compile requirements
      - id: uv-lock
      - id: uv-export
        args: ["--frozen", "--no-dev", "--output-file=requirements.txt"]
      - id: uv-export
        args: ["--frozen", "--all-groups", "--output-file=requirements.dev.txt"]
  - repo: local
    hooks:
      - id: unit-tests
        name: unit tests
        entry:
          uv run python -m pytest -p no:warnings --cov-report term-missing
          --cov=radio_gaga tests
        language: system
        pass_filenames: false
        always_run: true
      - id: pip-audit
        name: pip-audit
        entry: uv run pip-audit
        language: system
        pass_filenames: false
        always_run: true
